name: Verify Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/chemwolf6922/tiny-event-loop.git --recursive ../tev
      - run: make -C ../tev -j$(nproc)
      - run: sudo make -C ../tev install
      - uses: actions/checkout@v4
      - run: make -j$(nproc)
      - run: make -C tests -j$(nproc)
      - run: make -C tests run
